name: Deploy API
on: 
  push:
    branches: [ main ]
    tags-ignore:
      - '**'
    paths:
      - 'src/Api/**'
      - '!.github/workflows/**'
      - '.github/workflows/api.yml'

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]
    paths:
      - 'src/Api/**'
      - '.github/workflows/api.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: dotnet test LinkStand.sln

  deploy:
    needs: [ test ]

    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config ./scripts/fly/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
